In [1]:
import run_model

In [1]:
run  run_model.py --task traffic_state_pred --model mymodel --dataset HEAT

2021-04-16 17:44:23,885 - INFO - Log directory: ./trafficdl/log
2021-04-16 17:44:23,889 - INFO - Begin pipeline, task=traffic_state_pred, model_name=mymodel, dataset_name=HEAT
2021-04-16 17:44:25,175 - INFO - Loaded file HEAT.geo, num_nodes=41
2021-04-16 17:44:25,200 - INFO - Loaded file HEAT.rel, shape=(41, 41)
2021-04-16 17:44:25,203 - INFO - Loading ./trafficdl/cache/dataset_cache/point_based_HEAT_12_12_0.7_0.1_none_64_False_False_True.npz
2021-04-16 17:44:25,230 - INFO - train	x: (248, 12, 41, 1)y: (248, 12, 41, 1)
2021-04-16 17:44:25,236 - INFO - eval	x: (35, 12, 41, 1)y: (35, 12, 41, 1)
2021-04-16 17:44:25,239 - INFO - test	x: (71, 12, 41, 1)y: (71, 12, 41, 1)
2021-04-16 17:44:25,245 - INFO - NoneScaler


D:\aconda\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\aconda\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\aconda\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\aconda\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; 

2021-04-16 17:44:33,990 - INFO - factors	torch.Size([12, 41, 1])	cuda:0	True
2021-04-16 17:44:33,992 - INFO - rel_weights	torch.Size([80])	cuda:0	True
2021-04-16 17:44:33,995 - INFO - ffunc.weight	torch.Size([984, 492])	cuda:0	True
2021-04-16 17:44:33,998 - INFO - ffunc.bias	torch.Size([984])	cuda:0	True
2021-04-16 17:44:34,003 - INFO - dynamic.module.weight	torch.Size([1, 2])	cuda:0	True
2021-04-16 17:44:34,005 - INFO - dynamic.module.bias	torch.Size([1])	cuda:0	True
2021-04-16 17:44:34,008 - INFO - decoder.weight	torch.Size([1, 1])	cuda:0	True
2021-04-16 17:44:34,010 - INFO - Total parameter numbers: 485688
2021-04-16 17:44:34,015 - INFO - Start training ...
2021-04-16 17:44:34,018 - INFO - num_batches:4


C:\Users\admin\Desktop\深度学习\BUAA-DL2021-master\Bigscity-TrafficDL\trafficdl\model\traffic_flow_prediction\mymodel.py:119: UserWarning: masked_scatter_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:401.)
  inter.masked_scatter_(self.relations[:, 1:], weights)
D:\aconda\lib\site-packages\torch\nn\functional.py:1698: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


2021-04-16 17:44:36,897 - INFO - epoch complete!
2021-04-16 17:44:36,900 - INFO - evaluating now!
2021-04-16 17:44:37,037 - INFO - Epoch [0/100] train_loss: 0.0485, val_loss: 0.0094, lr: 0.010000, 3.0s
2021-04-16 17:44:37,055 - INFO - Saved model at 0
2021-04-16 17:44:37,058 - INFO - Val loss decrease from inf to 0.0094, saving to ./trafficdl/cache/model_cache/mymodel_HEAT_epoch0.tar
2021-04-16 17:44:39,490 - INFO - epoch complete!
2021-04-16 17:44:39,493 - INFO - evaluating now!
2021-04-16 17:44:39,628 - INFO - Epoch [1/100] train_loss: 0.0395, val_loss: 0.0128, lr: 0.010000, 2.6s
2021-04-16 17:44:42,241 - INFO - epoch complete!
2021-04-16 17:44:42,244 - INFO - evaluating now!
2021-04-16 17:44:42,421 - INFO - Epoch [2/100] train_loss: 0.0328, val_loss: 0.0200, lr: 0.010000, 2.8s
2021-04-16 17:44:44,900 - INFO - epoch complete!
2021-04-16 17:44:44,904 - INFO - evaluating now!
2021-04-16 17:44:45,037 - INFO - Epoch [3/100] train_loss: 0.0297, val_loss: 0.0259, lr: 0.010000, 2.6s
2021-04

2021-04-16 17:46:20,673 - INFO - epoch complete!
2021-04-16 17:46:20,677 - INFO - evaluating now!
2021-04-16 17:46:20,802 - INFO - Epoch [40/100] train_loss: 0.0083, val_loss: 0.0168, lr: 0.010000, 2.6s
2021-04-16 17:46:23,286 - INFO - epoch complete!
2021-04-16 17:46:23,288 - INFO - evaluating now!
2021-04-16 17:46:23,426 - INFO - Epoch [41/100] train_loss: 0.0083, val_loss: 0.0153, lr: 0.010000, 2.6s
2021-04-16 17:46:25,908 - INFO - epoch complete!
2021-04-16 17:46:25,911 - INFO - evaluating now!
2021-04-16 17:46:26,049 - INFO - Epoch [42/100] train_loss: 0.0082, val_loss: 0.0161, lr: 0.010000, 2.6s
2021-04-16 17:46:28,553 - INFO - epoch complete!
2021-04-16 17:46:28,556 - INFO - evaluating now!
2021-04-16 17:46:28,705 - INFO - Epoch [43/100] train_loss: 0.0082, val_loss: 0.0158, lr: 0.010000, 2.7s
2021-04-16 17:46:31,144 - INFO - epoch complete!
2021-04-16 17:46:31,148 - INFO - evaluating now!
2021-04-16 17:46:31,282 - INFO - Epoch [44/100] train_loss: 0.0082, val_loss: 0.0138, lr: 

2021-04-16 17:47:50,552 - INFO - epoch complete!
2021-04-16 17:47:50,555 - INFO - evaluating now!
2021-04-16 17:47:50,690 - INFO - Epoch [74/100] train_loss: 0.0035, val_loss: 0.0010, lr: 0.010000, 2.6s
2021-04-16 17:47:53,145 - INFO - epoch complete!
2021-04-16 17:47:53,148 - INFO - evaluating now!
2021-04-16 17:47:53,291 - INFO - Epoch [75/100] train_loss: 0.0034, val_loss: 0.0009, lr: 0.010000, 2.6s
2021-04-16 17:47:55,761 - INFO - epoch complete!
2021-04-16 17:47:55,763 - INFO - evaluating now!
2021-04-16 17:47:55,895 - INFO - Epoch [76/100] train_loss: 0.0033, val_loss: 0.0008, lr: 0.010000, 2.6s
2021-04-16 17:47:55,913 - INFO - Saved model at 76
2021-04-16 17:47:55,917 - INFO - Val loss decrease from 0.0008 to 0.0008, saving to ./trafficdl/cache/model_cache/mymodel_HEAT_epoch76.tar
2021-04-16 17:47:58,429 - INFO - epoch complete!
2021-04-16 17:47:58,432 - INFO - evaluating now!
2021-04-16 17:47:58,589 - INFO - Epoch [77/100] train_loss: 0.0033, val_loss: 0.0010, lr: 0.010000, 2.7

2021-04-16 17:48:57,074 - INFO - Evaluate result is saved at ./trafficdl/cache/evaluate_cache\2021_04_16_17_48_57_mymodel_HEAT.json
2021-04-16 17:48:57,089 - INFO - Evaluate result is saved at ./trafficdl/cache/evaluate_cache\2021_04_16_17_48_57_mymodel_HEAT.csv
2021-04-16 17:48:57,117 - INFO - 
         MAE  MAPE       MSE      RMSE  masked_MAE  masked_MSE  masked_RMSE  \
0   0.019531   inf  0.000578  0.024035    0.022527    0.000757     0.027520   
1   0.019872   inf  0.000600  0.024500    0.023015    0.000790     0.028100   
2   0.019860   inf  0.000600  0.024493    0.022997    0.000789     0.028092   
3   0.019995   inf  0.000609  0.024678    0.023190    0.000802     0.028322   
4   0.019654   inf  0.000594  0.024379    0.022703    0.000781     0.027949   
5   0.019735   inf  0.000599  0.024476    0.022818    0.000788     0.028068   
6   0.019643   inf  0.000594  0.024374    0.022685    0.000781     0.027941   
7   0.019827   inf  0.000606  0.024617    0.022946    0.000798     0.02

In [20]:
import torch
LL = torch.nn.Linear(2,4)
ss = torch.tensor([[3e-10,4e-10],[6e-10,4.55e-10]])
rrr = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tt = torch.tensor([[[0,1],[1,2]]])
print((LL(ss)*2).ceil().long())
print(rrr[LL(ss).ceil().long()[0,:],LL(ss).ceil().long()[1,:]])
print(rrr[tt,tt])

tensor([[ 0,  1,  0, -1],
        [ 0,  1,  0, -1]])
tensor([1, 5, 1, 1])
tensor([[[1, 5],
         [5, 9]]])
